### ISSUE TITLE
Documentation is Bad

### ISSUE THREAD

**Issue by dagrooms52** [sisl/BayesNets.jl#19]
I'm a Computer Science student and couldn't figure out how to use your library to save my life. 
Usually, libraries have a listing of the functions they contain. One helpful listing for your library would include "function setCPD(): takes some parameters, does something with them" although I do not see any sort of documentation for the functions linked to this page whatsoever. The documentation also does not include an example of creating a static Bayesian Network (like the kind my professor is having me recreate for a project). If you could include this sort of example, it would be very helpful, and your library would be oh so much more useful.
Update: even the source code is uncommented. Is everyone working on this project a self-taught programmer?

**Comment by tawheeler** [comment]
This package does not have any assigned developers and relies on volunteers to keep it up to date. The documentation could certainly use some love.

It does have some [examples](http://nbviewer.ipython.org/github/sisl/BayesNets.jl/blob/master/doc/BayesNets.ipynb). The documentation shows how to make a static Bayesian network with Bernoulli variables. You can also create `Discrete` and `Normal` CPDs, just follow the constructors in the source code. In the case of a discrete variable, the `parameterFunctuon` must map an `Assignment/Dict` to the corresponding list of probabilities for that variable, p(x|y).

**Comment by mykelk** [comment]
Now that 0.4 supports code documentation, we should probably use that.

**Comment by tawheeler** [comment]
So the most recent commits should alleviate much of the documentation confusion. 
The doc ijulia notebook needs to be updated

**Comment by mykelk** [comment]
Great! Thanks! You might want to include documentation about being able to read xdsl files (and include an example file so that we can get better test coverage of io.jl). Being able to read xdsl is a pretty nice feature (that @ermueller2000 is using).

**Comment by tawheeler** [comment]
Added xdsl input to doc in commit 1793be0
