### ISSUE TITLE
Is it possible to move `rand_table` from rejection sampling to sampling where known values are assigned?

### ISSUE THREAD

**Issue by tawheeler** [sisl/BayesNets.jl#21]
@ermueller2000 brought this to my attention.
The current implementation of `rand_table` uses rejection sampling, and passing `numSamples` gives the number of attempts, not the number of samples you want to end up with.
Alternatively we can set known values during the sampling procedure to speeds things up. The drawback is that we need a way to ensure that the probability of what we end up with is non-zero. This way we always end up with `numSamples` rows.

**Comment by mykelk** [comment]
Yeah, I like what you suggest. `numSamples` should really refer to how many you get out. But, we probably want a default timeout so that it doesn't run forever. Maybe `maxRejectedSamples` that defaults to `100 * numSamples`?

**Comment by tawheeler** [comment]
e698886 fixes this issue
