### ISSUE TITLE
Error in Julia v0.5

### ISSUE THREAD

**Issue by juliohm** [sisl/BayesNets.jl#34]
The current tag triggers an error:

```julia
bn = DiscreteBayesNet()
push!(bn, DiscreteCPD(:B, [0.1,0.9]))
push!(bn, DiscreteCPD(:S, [0.5,0.5]))
push!(bn, rand_cpd(bn, 2, :E, [:B, :S]))
push!(bn, rand_cpd(bn, 2, :D, [:E]))
push!(bn, rand_cpd(bn, 2, :C, [:E]))
```
>LoadError: MethodError: Cannot `convert` an object of type BayesNets.CPDs.CategoricalCPD{Distributions.Categorical{Float64}} to an object of type BayesNets.CPDs.CategoricalCPD{Distributions.Categorical}
This may have arisen from a call to the constructor BayesNets.CPDs.CategoricalCPD{Distributions.Categorical}(...),
since type constructors fall back to convert methods.
while loading In[2], in expression starting on line 2

 >in push!(::Array{BayesNets.CPDs.CategoricalCPD{Distributions.Categorical},1}, ::BayesNets.CPDs.CategoricalCPD{Distributions.Categorical{Float64}}) at ./array.jl:479
 in push!(::BayesNets.BayesNet{BayesNets.CPDs.CategoricalCPD{Distributions.Categorical}}, ::BayesNets.CPDs.CategoricalCPD{Distributions.Categorical{Float64}}) at /home/juliohm/.julia/v0.5/BayesNets/src/bayes_nets.jl:138

**Comment by zsunberg** [comment]
Thanks - will tag a new version later today. For now, the master branch (`Pkg.checkout("BayesNets")`) should work.

**Comment by zsunberg** [comment]
Should be fixed now

**Comment by pculbertson** [comment]
I am repeating this issue after updating all packages + checking out the master as suggested.
