### ISSUE TITLE
pushing to metadata

### ISSUE THREAD

**Issue by zsunberg** [sisl/BayesNets.jl#35]
@tawheeler , when I fix a small bug, as in f24c7e9ed06beae18ea795680e045d7e11a08204 , should I go ahead and tag and push to metadata, or should I just notify you and have you do it?

**Comment by tawheeler** [comment]
@zsunberg, for small things you can certainly tag and push.
For doc changes and things that don't affect people I typically just commit to the master branch and wait until the next needed tag.

**Comment by zsunberg** [comment]
Ok, sounds like a good plan
