### ISSUE TITLE
sumout columns with multiple values fails

### ISSUE THREAD

**Issue by mykelk** [sisl/BayesNets.jl#38]
```julia
b = DiscreteBayesNet()
push!(b, DiscreteCPD(:B, [0.1,0.9]))
push!(b, DiscreteCPD(:S, [0.5,0.5]))
push!(b, rand_cpd(b, 3, :E, [:B, :S]))
push!(b, rand_cpd(b, 3, :D, [:E]))
push!(b, rand_cpd(b, 3, :C, [:E]))

a = Assignment(:B=>2, :D=>2, :C=>2)

T = table(b,:B,a)*table(b,:S)*table(b,:E,a)*table(b,:D,a)*table(b,:C,a)
sumout(T, :E)
```
This produces:
```
LoadError: MethodError: no method matching join(::DataFrames.SubDataFrame{Array{Int64,1}}, ::DataFrames.SubDataFrame{Array{Int64,1}}, ::DataFrames.SubDataFrame{Array{Int64,1}}; on=Symbol[:B,:S,:D,:C])
Closest candidates are:
  join(::Any...) at strings/io.jl:128 got unsupported keyword argument "on"
  join(!Matched::IO, ::Any, ::Any) at strings/io.jl:115 got unsupported keyword argument "on"
  join(!Matched::IO, ::Any, ::Any, !Matched::Any) at strings/io.jl:99 got unsupported keyword argument "on"
  ...
while loading In[12], in expression starting on line 11

 in sumout(::DataFrames.DataFrame, ::Symbol) at C:\Users\Mykel\.julia\v0.5\BayesNets\src\DiscreteBayesNet\factors.jl:43
```
If you do `sumout(T, :B)`, then it works just fine since B takes on only two different values. E takes on three values. There seems to be some kind of issue with `j = join(g..., on=remainingvars)` on line 43 [here](https://github.com/sisl/BayesNets.jl/blob/906770b21daa9a0745e6274cf53d81ffedd33f6a/src/DiscreteBayesNet/factors.jl).

**Comment by tawheeler** [comment]
The code for the discrete factor operations tends to be complicated and hard to read. I think this was originally @mykelk 's implementation - maybe you have a better feel for how these work than I do. Always requires banging your head against the wall a few times before you figure it out.
I don't think I will get around to this in the near future unless I get a lot of push to do so.

**Comment by tawheeler** [comment]
I think PR https://github.com/sisl/BayesNets.jl/pull/42 fixes this.

**Comment by tawheeler** [comment]
The code now produces:

```
julia> sumout(T, :E)
2×5 DataFrames.DataFrame
│ Row │ B │ S │ D │ C │ p         │
├─────┼───┼───┼───┼───┼───────────┤
│ 1   │ 2 │ 1 │ 2 │ 2 │ 0.038975  │
│ 2   │ 2 │ 2 │ 2 │ 2 │ 0.0501872 │
```
