### ISSUE TITLE
Sampling with FunctionalCPD

### ISSUE THREAD

**Issue by jpfairbanks** [sisl/BayesNets.jl#58]
Thanks for developing this great package. As a LightGraphs maintainer, I am happy to see this great application using LightGraphs.

I was building some networks that use the FunctionalCPD because I would like to have nodes similar to the LinearGaussianCPD but where the output is a binary variable. 

I made a FunctionalCPD where the output is a Bernoulli variable with a mean dependent on the parent values of the node.

I have a minimal replicating example.
```
Pkg.checkout("BayesNets")
using BayesNets
using LightGraphs

a = StaticCPD(:a, Bernoulli(0.5))
b = StaticCPD(:b, Bernoulli(0.6))
c = FunctionalCPD{Bernoulli}(:c, [:a,:b], seq->Bernoulli(mean(values(seq))))
bn = BayesNet()
push!(bn, a)
push!(bn, b)
push!(bn, c)
rand(bn, 20, :a=>1, :b=>1)
```

Which I expect to return a table where every row is (1,1,1), however I see
```
	a	b	c
1	1	1	1
2	1	1	1
3	1	1	0
4	1	1	1
5	1	1	1
6	1	1	1
7	1	1	1
8	1	1	1
9	1	1	0
10	1	1	1
11	1	1	0
12	1	1	0
13	1	1	1
14	1	1	1
15	1	1	1
16	1	1	1
17	1	1	1
18	1	1	0
19	1	1	1
20	1	1	1
```

Is this a missapplication of the FunctionalCPD type? Or something wrong with the sampling process? Or something else?

**Comment by tawheeler** [comment]
Thanks!
I think the issue is that `mean(values(seq))` will take the mean over all entries in `seq`, which can include and uninitialized `c` from a previous sample. To fix it you can do the following:

```julia
c = FunctionalCPD{Bernoulli}(:c, [:a, :b], seq->Bernoulli((seq[:a] + seq[:b])/2))
```

which produces all ones.

**Comment by jpfairbanks** [comment]
Thanks for letting me know what was wrong!

I'm a little confused about what information is contained in the argument to the FunctionalCPD function field. I know it is a Dict{Symbol,Any} but what is supposed to be in that Dict?

**Comment by tawheeler** [comment]
The argument is an `Assignment`, which will map variable Symbols to their values.
We use `rand!` when making multiple samples, which causes there to be stale values which are overwritten as you progress through the topological order.
