### ISSUE TITLE
heads-up 0.6 changes to LightGraphs

### ISSUE THREAD

**Issue by sbromberger** [sisl/BayesNets.jl#64]
Hi all,

LightGraphs is preparing for a fairly large upgrade with Julia 0.6, and I wanted to make you aware of what we're doing. Very few things are breaking, but there will be some potential performance improvements that you might be able to take advantage of.

In a nutshell: we're abstracting `Graph` and `DiGraph`, renaming them to `SimpleGraph` and `SimpleDiGraph`*, and parameterizing vertex indices to `<: Integer`. This will allow you to create, e.g.,  `SimpleGraph{UInt8}`s that will be much more space-efficient if you have graphs that are < 256 vertices.

*While we plan on more abstractions (e.g., for weighted graphs) in the future, for now `Graph` and `DiGraph` will continue to work and will continue to default to `SimpleGraph`, and the default parameterization for both `Simple(Di)Graph`s and `(Di)Graph`s will be `Int`.

Feel free to review the (very long) WIP at https://github.com/JuliaGraphs/LightGraphs.jl/pull/541 - your feedback would be greatly appreciated.

**Comment by mykelk** [comment]
Updated a while ago.
