### ISSUE TITLE
Use package-local wrapper type instead of extending Base (or other packages') methods on DataFrame

### ISSUE THREAD

**Issue by tkelman** [sisl/BayesNets.jl#67]
Since https://github.com/sisl/BayesNets.jl/blob/5febf756d38194712cfb8c0c2294252931611afa/src/DiscreteBayesNet/tables.jl does a `const Table = DataFrame`, all method extensions on `Table` are global and change the behavior of other unrelated code that uses DataFrames, just from importing BayesNets whether or not it's using this package. This is [discouraged](https://docs.julialang.org/en/latest/manual/style-guide.html#Avoid-type-piracy-1).

If `Table` were instead a wrapper struct that delegated the relevant operations to a single DataFrame field, then you could define methods on `BayesNets.Table` however you like and not be at risk of changing any other code's behavior.

Same issue with https://github.com/sisl/BayesNets.jl/blob/5febf756d38194712cfb8c0c2294252931611afa/src/ProbabilisticGraphicalModels/assignments.jl#L7 and https://github.com/sisl/BayesNets.jl/blob/5febf756d38194712cfb8c0c2294252931611afa/src/ProbabilisticGraphicalModels/nodenames.jl#L5 as well

and https://github.com/sisl/BayesNets.jl/commit/3cd56dc6a99e0a650177577dda3821b1fd7a0244#commitcomment-22494521 should probably be submitted upstream in DataFrames?

**Comment by tawheeler** [comment]
@mykelk - maybe this can be delegated to another SISLer?

**Comment by mykelk** [comment]
@hamzaelsaawy said he can handle these issues.

**Comment by tkelman** [comment]
Yep these have all come up in past discussions, probably easier to track all in one place though rather than a bit scattered
