### ISSUE TITLE
Julia 1.0 support

### ISSUE THREAD

**Issue by jzicker** [sisl/BayesNets.jl#76]
Any plans to move to Julia 1.x ?

**Comment by mykelk** [comment]
I updated the travis script, and it looks like it is failing on some of the tests. We'll get this working; thanks for filing the issue.

**Comment by jzicker** [comment]
thank you.  I'm looking forward to building a few networks once you port to Julia 1.0

**Comment by mykelk** [comment]
@Shushman fixed it, and now all tests pass on Julia 1.0 and 1.1. So, right now, you can get it from master. He'll tag a release shortly.

**Comment by jzicker** [comment]
so awesome.  thank you
